/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesTermsOfServiceRouteImport } from './routes/resources/terms-of-service'
import { Route as ResourcesPrivacyPolicyRouteImport } from './routes/resources/privacy-policy'
import { Route as ResourcesCookiePolicyRouteImport } from './routes/resources/cookie-policy'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTermsOfServiceRoute = ResourcesTermsOfServiceRouteImport.update({
  id: '/resources/terms-of-service',
  path: '/resources/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPrivacyPolicyRoute = ResourcesPrivacyPolicyRouteImport.update({
  id: '/resources/privacy-policy',
  path: '/resources/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCookiePolicyRoute = ResourcesCookiePolicyRouteImport.update({
  id: '/resources/cookie-policy',
  path: '/resources/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/programs': typeof ProgramsRoute
  '/resources/cookie-policy': typeof ResourcesCookiePolicyRoute
  '/resources/privacy-policy': typeof ResourcesPrivacyPolicyRoute
  '/resources/terms-of-service': typeof ResourcesTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/programs': typeof ProgramsRoute
  '/resources/cookie-policy': typeof ResourcesCookiePolicyRoute
  '/resources/privacy-policy': typeof ResourcesPrivacyPolicyRoute
  '/resources/terms-of-service': typeof ResourcesTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/programs': typeof ProgramsRoute
  '/resources/cookie-policy': typeof ResourcesCookiePolicyRoute
  '/resources/privacy-policy': typeof ResourcesPrivacyPolicyRoute
  '/resources/terms-of-service': typeof ResourcesTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/manifesto'
    | '/programs'
    | '/resources/cookie-policy'
    | '/resources/privacy-policy'
    | '/resources/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/manifesto'
    | '/programs'
    | '/resources/cookie-policy'
    | '/resources/privacy-policy'
    | '/resources/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/docs'
    | '/manifesto'
    | '/programs'
    | '/resources/cookie-policy'
    | '/resources/privacy-policy'
    | '/resources/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ManifestoRoute: typeof ManifestoRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesCookiePolicyRoute: typeof ResourcesCookiePolicyRoute
  ResourcesPrivacyPolicyRoute: typeof ResourcesPrivacyPolicyRoute
  ResourcesTermsOfServiceRoute: typeof ResourcesTermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/terms-of-service': {
      id: '/resources/terms-of-service'
      path: '/resources/terms-of-service'
      fullPath: '/resources/terms-of-service'
      preLoaderRoute: typeof ResourcesTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/privacy-policy': {
      id: '/resources/privacy-policy'
      path: '/resources/privacy-policy'
      fullPath: '/resources/privacy-policy'
      preLoaderRoute: typeof ResourcesPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/cookie-policy': {
      id: '/resources/cookie-policy'
      path: '/resources/cookie-policy'
      fullPath: '/resources/cookie-policy'
      preLoaderRoute: typeof ResourcesCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ManifestoRoute: ManifestoRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesCookiePolicyRoute: ResourcesCookiePolicyRoute,
  ResourcesPrivacyPolicyRoute: ResourcesPrivacyPolicyRoute,
  ResourcesTermsOfServiceRoute: ResourcesTermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
